remote_theme: cotes2020/jekyll-theme-chirpy
title: Futuro Sustentável Digital
description: Portal independente de notícias sobre sustentabilidade e economia circular
url: "https://ambisocial.github.io"
baseurl: "/futuro-sustentavel-digital"
author: Redação Futuro Sustentável Digital
email: contato@futuro-sustentavel-digital.com
lang: pt-BR
timezone: America/Sao_Paulo
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-archives
markdown: kramdown
highlighter: rouge
paginate: 10
paginate_path: "/page:num/"
